# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Burnman
tagline:          'I Am What I Am'
description:      ''
url:              http://burnman.github.io/
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.1

github:           https://github.com/burnman
  repo:           https://github.com/poole/lanyon
