# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Burnman
tagline:          'I Am What I Am'
description:      ''
url:              http://burnman.github.io/
paginate:         5

author:
  name:           'Burnman'
  url:            http://burnman.github.io/

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/burnman/burnman.github.com
